# Generated by Django 5.2.5 on 2025-08-31 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.profile'),
            preserve_default=False,
        ),
    ]
